### ISSUE TITLE
Compare algorithms with ANOVA

### ISSUE THREAD

**Issue by stellentus** [ZerkTheMighty/551Project#3]
I think this link provides the best instructions for ANOVA in Python.
http://www.statsmodels.org/stable/examples/notebooks/generated/interactions_anova.html
But it might be easier to just do it in Matlab. I assume there will be more basic tutorials available for Matlab.

**Comment by stellentus** [comment]
Or possibly do it with scipy, though this example just shows a confirmation of the NULL hypothesis, not have to do pairwise comparisons...
http://www.randalolson.com/2012/08/06/statistical-analysis-made-easy-in-python/
I haven't read that page thoroughly.

**Comment by ZerkTheMighty** [comment]
You gone done good!
